default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: bitcoin-project-444715
      dataset: raw_dataset
      threads: 4
      keyfile_json:
        type: service_account
        project_id: bitcoin-project-444715
        private_key_id: 3e1aa1ec4488e80ad1118e34bf13ba27c65b8b48
        private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDGGOJHJX3PdMFX\nKySEAeozuIkFXYL9RzH0arfPGN1LoTxW6ip/qxlyU0qDolgb/td7P0F9Aco1sfcb\ngE5deYvwWrnbD4Gpz7nJp6EIgsD2y8646KRfm5lg8rSpSxkymoHgIZsSpY8nIXHd\n64LfoXcZhzzuTQ17xno0H4ogp5WfFXkkUfNSK3XA2FryE6M4KZE/zNGWNNEpenmU\nwy0x2a3bCpUdj8jRsFPVde6tH4O/Vp2Y2DGFz1OvCU93dxubCvkSj1iFjCyw1QjV\nAud8iFe08mbfqwWPXvcfp5bwl9IyqAQEjJx/ckL2aGBhKH8z3sDKgwF9UgvlwyK+\n6pPBM6QRAgMBAAECggEAImAaEAeI+/GCRWqWpROh/QSmPliaTPJIUGYebGEfsaqS\ninCLHGln+odKlGodCQqhgOEar6MaYFP4Ef0jXCQl7PkJbGKV+Q4zarNchdoOuyTl\nw/+W2oJpTMIBKKl//2CBbg/W1ZcGLt+mX0Cpjr35qWPm5mFXmCV6ekYI1Z7PH3Iv\nw2i7whFPStXwynN3mHnTfgpsHXwhd1W1YD7mCeyZ601Ci1JTcIHYgXz7Vrl+yDCd\nuiE446AcjQUdzEOL//F9QFuLGd3ZXmXshLRppFSqKyQK2m1uq5FvvW7OBy2oomRB\nulwPTwpnhS4YgyvageTS2fPNt6+CFYThVSLdlijrywKBgQDp6Or/54o2opib3QXY\ngrXm9t/s75tSLzCzQbygoWSJHfOqONboO194yAr9lV1LHS2KYqvseoZBWW3R4Lqt\n+5u7NSLBVT+EPZacxZHi+twksIppnnvMrEeYbev2chD+ewRSr5YR6KscToCJsPlr\n4eOpQ/7nUA75KeiGeO6XbFuLOwKBgQDYziXV68sS+M8ULJUuCZM5vFO6hkqkna0h\njIW3JZMqKnPVNsxU6eQEc+45/94ZqolgZ9fmb6XyG5U8nXhcqVEeSUa9fgGxZHtN\nsNqpnXo3AYUm1QPutDMbadsnV+rELxrTlxS8PqfwW9n6p2WGMluChcrNwQyaZHJb\nTtCxbWchIwKBgQCz5B+nQ4j2T8ISTL9MLep7gG3iqLvJTuWjVvEckELjeReGWERf\nQhpAp4hcUdz4Aa6eeRhDvE84PvDIso6fc5vnNAxQp6E7sKn+U6vI5qkbxnIMnIgV\ndoFxZ0hLtpn/PNisRsGhcFD4ah9MxcBtCcKu0M5fUyDQ2zwq/yJvbjRRNQKBgQDA\nWST4RdpFWrleDK/NyHD2KD+gnMRciAeyXBnGA3AtWLyrzZI7Q8corDIPAxLpcoOv\nJHJH34Y65n3g6VR/4Tg2xowcUk7uM1ex9dYJ5c0oQBECArsabIVrLN9iaH3A0Inc\nb43V9UDJ3rPlzd4k0Uie5FSpdzzXPYa3u5Ur1QRKQQKBgQDpbgVgvkotDeVWfPlH\nvpyxVTjMWYM3H64z8SzGpqawQ2ZvNXNc/edxtfTk2BsVRG6JyaXrtPhQw6bqv8ff\nRrtNBx0FxEcrMBoM+j0ko1EX5WpfloZfLWPxhqnPVXtliPrAXOJs/NfILeM+1ek8\n7RbJ8DSPR69ku7D3fUdsaxVDSA==\n-----END PRIVATE KEY-----\n"
        client_email: "=kdrhl336@bitcoin-project-444715.iam.gserviceaccount.com"
        client_id: "116402945451402178304"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/kdrhl336%40bitcoin-project-444715.iam.gserviceaccount.com"
        universe_domain: googleapis.com
      priority: interactive
