name: Test Astro Deployment (Push Only)

on:
  push:
    branches: [ "main" ]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.4
        env:
          ASTRONOMER_KEY: ${{ secrets.ASTRO_API_TOKEN }}
        with:
          workspace: ${{ vars.WORKSPACE_ID }}
          deployment-id: ${{ vars.DEPLOYMENT_ID }}
          action: deploy
