version: 2

models:
  - name: bitcoin_model
    description: "bitcoin model"
    columns:
      - name: block_hash
        tests:
          - unique
          - not_null
      - name: block_timestamp
        tests:
          - not_null
